import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "../globals.css";

const interFont = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const lexendFont = Lexend({
	variable: "--font-lexend",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "BigBold Inc. - Auth",
	description: "Generated by create next app",
};

export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${interFont.variable} ${lexendFont.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
