import type { Metadata } from "next";
import { Inter, Lexend } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const interFont = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const lexendFont = Lexend({
	variable: "--font-lexend",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${interFont.variable} ${lexendFont.variable} antialiased`}
			>
				<div>
					<div>
						<div className="p-3">
							<Navbar />
						</div>
						{children}
						<Footer />
					</div>
				</div>
			</body>
		</html>
	);
}
